### ISSUE TITLE
Incorrect Use of asyncio.timeout in rabbitmq.py File

### ISSUE THREAD

**Issue by gak3r** [MythicMeta/MythicContainerPyPi#10]
Hello 🙋‍♂️,

I've encountered an issue within the `rabbitmq.py` file, specifically regarding the use of `asyncio.timeout`. The current implementation attempts to use `asyncio.timeout` as a context manager, which is incorrect, as the `asyncio` module doesn't have a `timeout` attribute. This misusage leads to a critical error in the code.

In the existing code, the problematic part is:
```python
async with asyncio.timeout(20):
    result = await future
    return result
```
❌

I suggest the following correction to implement the timeout functionality accurately:
```python
try:
    result = await asyncio.wait_for(future, timeout=20)
    return result
except asyncio.TimeoutError:
    # Handle the timeout
    future.cancel()
    logger.error("hit timeout waiting for RPC response, retrying...")
```
✅

This modification correctly applies a 20-second timeout to the `await future` operation. If the future does not resolve within this timeframe, an `asyncio.TimeoutError` is raised, allowing for appropriate error handling. This change should resolve the issue with the incorrect usage of `asyncio.timeout`.

Could you please address this issue 🛠 by updating the `rabbitmq.py` file accordingly?

Thank you 🙏 for your attention to this matter and for maintaining the quality of the codebase!

Best regards,
Gak3r 💼

**Comment by its-a-feature** [comment]
Good catch! Updated in version 0.3.6
