### ISSUE TITLE
PayloadType `wrapper_payload` attribute has the wrong documentation

### ISSUE THREAD

**Issue by Dramelac** [MythicMeta/MythicContainerPyPi#5]
Hello,

In the class PayloadType there is an attribute named `wrapped_payload` that is supposed to be the UUID of the payload to wrap but instead we got the binary data encoded in base64.

Link to the error: 
https://github.com/MythicMeta/MythicContainerPyPi/blob/main/mythic_container/PayloadBuilder.py#LL458C9-L459C87

It's first a documentation error but could it be possible to **also** have this information (with another attribute for example) to allows us to fetch more metadata information regarding the payload over MythicRPC for example.

Thank you very much for the help!

**Comment by its-a-feature** [comment]
Can you test out the new `mythic-container==0.2.11-rc6` PyPi package and see if that works as you expect? If you're using docker images from me, you can add a line to your Dockerfile that says `RUN pip install mythic-container==0.2.11-rc6` to force the container to install that specific version.

**Comment by Dramelac** [comment]
Thanks for your response! 

I tried to implement it in a wrapper by adding the `RUN ...` command of the Dockerfile of the concerned module but I get a "None" in "wrapped_payload_uuid".
Should I add the `RUN` command to other Mythic modules?

Thank you!

**Comment by its-a-feature** [comment]
Great question! This modification required two things - an update to the PyPi package and an update to the Mythic server (to actually send the data to the PyPi package). You'll need to make sure you pull the latest from the master branch of `Mythic` as well to get the value to populate

**Comment by Dramelac** [comment]
After updating Mythic, It seems to work ! 
Thank you very much!
