### ISSUE TITLE
Discrepancy between repository and PyPi package import statements

### ISSUE THREAD

**Issue by gak3r** [MythicMeta/MythicContainerPyPi#9]
Hello 🙋‍♂️,

I've noticed a discrepancy 🤔 between the import statements in the MythicContainerPyPi repository and the version that's published on PyPi.

In the repository, the correct import statement is used:
```python
import mythic_container.grpc.translationContainerGRPC_pb2 as translationContainerGRPC__pb2
```
✅

However, in the PyPi package, the import statement is:
```python
import translationContainerGRPC_pb2 as translationContainerGRPC__pb2
```
❌

This leads to an error (`ModuleNotFoundError`) 😞 when attempting to use the package installed from PyPi. It seems that the version in the repository has been updated 🔄, but the version on PyPi has not been updated accordingly.

Could you please address this issue 🛠 by publishing the corrected version to PyPi?

Thank you 🙏 for your attention to this matter!

Best regards,
Gak3r 💼

**Comment by its-a-feature** [comment]
Ah, I thought i had fixed that before creating the package! Thanks for the catch! I just pushed a new version, `0.3.2` which should have that resolved. Docker images should be updated shortly to include the change
